### ISSUE TITLE
Functionality Improvements for the SAML SDK

### ISSUE THREAD

**Issue by ChamathNS** [asgardio/asgardio-java-saml-sdk#3]
**Description:**

A few improvements have been identified for the SAML SDK which would add to the scope of the functionality that could be utilized by the developer. 

**Tasks:**

The following are the main tasks that has been identified for the first phase of the improvements.

- [ ] Add support for an error page via the properties file.
      A page to customize the redirect page upon error response.

- [ ] Add support for a target page.
      A page to customize the redirect page upon successful authentication.

- [ ] Refactor the SSOAgentConfigs and SSOAgentConfig classes.
